# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'https-lenpaul-github-io-lagrange'

google-ID: 'UA-112060364-1'

menu:
# Building About separately to link homepage
# - {name: 'About', path: 'menu', url: 'about.html'}
- {name: 'Projects', path: 'menu', url: 'projects.html'}
- {name: 'CV', path: 'menu', url: 'CV.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github', link: 'https://www.github.com/afzalhmd14'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/afzal-ahmad-351088114/'}
- {icon: 'envelope', link: 'mailto:afzalhmd14@gmail.com'}
# - {icon: 'rss-square', link: '/rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'


